nodes:
  - id: "node_0"
    ip: 127.0.0.1
    port: 32770
    weight: 1
  - id: "node_1"
    ip: 127.0.0.1
    port: 32771
    weight: 1
  - id: "node_2"
    ip: 127.0.0.1
    port: 32772
    weight: 1